### ISSUE TITLE
백슬래시 문제

### ISSUE THREAD

**Issue by swcheon** [RedgooseDev/goose#101]
1.0.4 버전에서도 글 수정 페이지에서 백슬래시가 사라지는 문제는 여전하네요. ㅠㅠ

**Comment by RedgooseDev** [comment]
이상하군요... 확인 다 했는데.. 브라우저 캐쉬가 남아있는거 아닌가요?

**Comment by swcheon** [comment]
아 해결이 됐습니다. 제가 괜히 시간을 뺐었네요. 고맙습니다!

**Comment by RedgooseDev** [comment]
다행이네요. ㅎㅎ~ 역시 수정했는데도 안된다고 할때 캐쉬 물어보면 다 먹히네요. :)
