### ISSUE TITLE
DB 접속 시 기본 포트가 아닌 다른 포트 사용 시

### ISSUE THREAD

**Issue by swcheon** [RedgooseDev/goose#115]
안녕하세요, 평소에 Goose 정말 잘 사용하고 있습니다. 감사합니다! ^^
다름이 아니라 제가 퍼니오 호스팅(http://www.fun25.co.kr)에서 새롭게 Goose를 설치하려고 합니다.
여긴 MySQL 기본 포트(3306)를 사용하지 않고 다른 포트를 사용합니다. 이런 경우 어떻게 설치를 해야 하는 지 궁금합니다. 따로 설정을 할 수 있나요?

**Comment by RedgooseDev** [comment]
서버 환경이 대단히 좋은 곳이네요. 갈아타고싶은 유혹이 확 올라오는 곳이네요 ㅎㅎ~ 
방금 로컬호스트에서 mysql 포트번호를 변경하고 실행해봤더니 특별히 오류가 나지 않았습니다. (포트를 바꾸고 테스트 해본적이 없었네요. ^^;)

제가 호스팅에서 설치해본것중에 가장 어려웠던곳이 가비아였는데 php 버전이 낮고, mysql 호스트가 localhost가 아닌 다른 ip였습니다. -_-;
호스트만 체크해두면 될거 같습니다. apache에서야 큰 문제는 없을거 같구요. :)

**Comment by swcheon** [comment]
Goose 최초 설치를 할 때 DB hostname 필드에 localhost:1234 이런 식으로 호스트네임과 포트를 함께 넣으면 되나요? 포트를 넣을 수 있는 필드가 따로 없어서.. 어떻게 해야 할 지 모르겠네요 ^^;

**Comment by RedgooseDev** [comment]
61172bd
필드를 수정해서 master 브런치에 커밋했습니다. dev 브런치에 커밋하고 둬야하는데 좀 실수했네요. ㅠㅠ
db관련 메뉴얼에서 보니 포트넣는 부분이 있어서 급하게 넣어봤습니다.

이제 시도해보세요. 안되면 물어봐주세요 ㅎㅎ

**Comment by swcheon** [comment]
설치를 시도해 봤더니 잘 됩니다. 신속한 피드백 감사합니다! :)
