### ISSUE TITLE
ext 폴더가 vendor 로 변경된건가요..

### ISSUE THREAD

**Issue by 76charles** [RedgooseDev/goose#125]
깃에서 다운받은거로 설치해서 구스_데모 돌려보고 있는데요..

그림파일 읽어오지 못해서 보니 ext 폴더 아래의 Parsedown 폴더에서 클래스파일을 읽어오게
되어 있어서 vendor로 수정하니 나오네요.. 아직 섬네일은 안나오고 있는데... 
아직 구조파악이 안되서... 찾아보고 있네요..

**Comment by RedgooseDev** [comment]
중간에 ext->vendor로 디렉토리 변경한적이 있었는데 전부 다 고쳤는데 어떤 부분인가요?
저도 확인이 필요할거 같네요.

http://redgoosedev.github.io/goose/
이 페이지가 도움이 될거라고 생각되네요. 자세한건 각 페이지에 `?` 버튼을 누르면 모듈별로 도움말을 볼 수 있을거예요 ㅎㅎ

**Comment by RedgooseDev** [comment]
그리고 article 모듈에서 기본 스킨은 첨부파일만 되구요. 아래 그림과 같이 nest skin과 article skin을 변경해주면 썸네일 이미지를 만들 수 있는 글쓰기 화면을 볼 수 있을거예요 ;)

![cap 2016-01-25 15-31-46-596](https://cloud.githubusercontent.com/assets/1978100/12543993/c9428ad2-c378-11e5-86af-06b0d0712388.png)

**Comment by 76charles** [comment]
도큐먼트 만들어 놓으신것 중에서 "goose demo 소스 다운로드" 에 소스 다운한 것중에 Layout.html 에 있었습니다.  makedown 아티클 스킨을 쓰니까 그림파일이 업로드가 안되더라고요... 제쪽 서버가 문제인지.. 그걸 tinymcd edit로 넣어서 아티클 스킨을 바꿔주니 업로드가 되던데요.. 참고로 서버는 윈도우7에서 WAMP라는걸 사용중입니다..
![image](https://cloud.githubusercontent.com/assets/16873641/12543997/d39eb65e-c378-11e5-9196-d49cdd98e56f.png)

**Comment by 76charles** [comment]
클라이언트 화면이구요
![image](https://cloud.githubusercontent.com/assets/16873641/12544095/f2a8df10-c379-11e5-9954-0a58bc2d0fe1.png)

관리자? 화면입니다.
![image](https://cloud.githubusercontent.com/assets/16873641/12544110/18d91894-c37a-11e5-8591-50df1f60eaf1.png)

**Comment by RedgooseDev** [comment]
업데이트하면서 `goose_demo.zip` 파일 존재를 까맣게 잊고 있었네요. 큰 부분이 업데이트 되었는데 적용을 못한게 한두군데가 아녔나봐요 ㅠㅠ
관리자에서 썸네일 이미지가 나오면 goose_demo.zip에서 문제가 있는거네요. 흑~

**Comment by 76charles** [comment]
힘내세요~! 홧팅!! 제가 자바스크립트는 잘 몰라서 모듈이나 이런거 만들지는 못하지만.. 응용은 좀 합니다. ㅎㅎㅎㅎ 회사에서 제 부서의 업무전용사이트를 제 컴퓨터를 서버로 해서 하나 해볼라는거니깐요.. 하다 안되거나 모르는건 질문드리겠습니다. ^^

**Comment by RedgooseDev** [comment]
[goose_demo.zip](https://github.com/RedgooseDev/goose/files/102867/goose_demo.zip)

에고에고... 수정 버전 우선 여기다가 첨부로 올려놓을께요 ㅎㅎ
<?php 안붙었다고 오류가 막 나는바람에 원인찾느라고 해메고 있었네요 ㅠㅠ

**Comment by RedgooseDev** [comment]
다른일과 같이 수정하느라 정신이 없네요. 일단 링크게 있었던 파일도 수정 끝냈습니다.
메뉴얼에 있는 페이지를 소홀히 했더니 이렇게 당했네요. 이슈 남겨주셔서 정말로 감사합니다. ㅠ_ㅠ
이 이슈는 일단 닫도록 할께요. 다른 뭔가 막히는거 있으면 이슈 남겨주시면 확인해볼께요~

**Comment by 76charles** [comment]
네~ 감사합니다~ ^^
