### ISSUE TITLE
Do i have to make goose directory ?

### ISSUE THREAD

**Issue by moreworld** [RedgooseDev/goose#127]
Thank you so much for your good software as free.
I like to make my own website by your s/w.

I tried it, everything is O.K. except user screen.

Do I have to make goose folder ?
It is compulsory.
Thanks you so much for your answer in advance.

Have a nice day.

**Comment by RedgooseDev** [comment]
php스쿨의 더넓은세상님이네요. ㅎㅎㅎ 아주 긴장했습니다. ㅠㅠ
php스쿨에서 댓글을 올렸습니다만 goose 파일들을 root로 옮기고 설치하면 root에서 사용할 수 있습니다.
goose 페이지는 로그인 하도록 막혀있어서 보통 root로 넣진 않더라구요. xe나 워드프레스는 root에 넣어야지 `abc.com`으로 접속하면 바로 뜨겠지만 goose는 관리와 출력 부분이 분리되어있어서 출력하는 프로그램을 root에서 작성해서 사용하시면 됩니다 :)

**Comment by moreworld** [comment]
답변 감사 드립니다.
제가 조금전에 해 보니 잘 안되든데요.
 
혹시  제가 테스트 하고 있는 호스팅 도메인이 dlpsystem.kr 이고 ID 가 dlpsystem
비밀번호가 zxcv0103 입니다.
 
FTP로 접속해서 어떻게 세팅해면 되는지 한번 봐 주심 제가 쉽게 따라 할 수 있을 것 같습니다.
﻿바쁘신데 번거롭게 해 드려서 죄송합니다.
 
만들어 놓으신 것이 굉장히 빨라서 이미지를 보여주기는 최적이라고 생각이 듭니다.
이번 기회에 저도 좀 공부를 해 볼까 합니다.
 
감사합니다.
 
  
Best Regards 
President - Heo/YunYoung 
KICT Group | Marketing | moreworld@kictgroup.com | +82-10-9636-3833 
We are Korean high technology manufacturer and exporter. 
Email) moreworld@kictgroup.com, moreworld@marinebio.kr 
Web) www.kictgroup.com 
Tel) 82-70-4837-1730 Fax) 82-504-056-3833
SKYPE:kictgroup
  
-----Original Message-----

**Comment by RedgooseDev** [comment]
제가 질문을 오해했었네요 :)

가장처음 phpschool에서 올리신 질문이 ` root 디렉토리에 설치하니 설치가 되는데 그럼 직접 유저들에게 보여주는 화면은 어떻게 세팅을 하는지 잘 이해가 안됩니다.` 라고 하셨는데 말이죠. ㅎㅎ

/goose : 이렇게 접속되도록 그대로 두고...
/ : 앱으로 접속되게 하면 방문객이 글들을 볼 수 있을겁니다.

일단 제가 하던일좀 처리끝나고 세팅해보겠습니다. :)

**Comment by moreworld** [comment]
﻿예 감사 드립니다.
dlpsystem.kr 로 들어가 보시면 제가 어제 저녁에 테스트로 해 본 것들이 있습니다.
​그런데 이것을 실제로 이미지들 다 올리고 나서 dlpsystem.kr로 사용자들에게 보여주고 싶은데 그것을 어떻게 처리해야 할지 모르는 것입니다.
​
​감사합니다. 
 
  
Best Regards 
President - Heo/YunYoung 
KICT Group | Marketing | moreworld@kictgroup.com | +82-10-9636-3833 
We are Korean high technology manufacturer and exporter. 
Email) moreworld@kictgroup.com, moreworld@marinebio.kr 
Web) www.kictgroup.com 
Tel) 82-70-4837-1730 Fax) 82-504-056-3833
SKYPE:kictgroup
  
-----Original Message-----

**Comment by moreworld** [comment]
이메일은   moreworld@kictgroup.com 이구요  비밀번호는  zxcv0103 입니다.
감사합니다.
==============================================
​예 감사 드립니다. 
dlpsystem.kr 로 들어가 보시면 제가 어제 저녁에 테스트로 해 본 것들이 있습니다.
​그런데 이것을 실제로 이미지들 다 올리고 나서 dlpsystem.kr로 사용자들에게 보여주고 싶은데 그것을 어떻게 처리해야 할지 모르는 것입니다.
​
​감사합니다. 
 
  
Best Regards 
President - Heo/YunYoung 
KICT Group | Marketing | moreworld@kictgroup.com | +82-10-9636-3833 
We are Korean high technology manufacturer and exporter. 
Email) moreworld@kictgroup.com, moreworld@marinebio.kr 
Web) www.kictgroup.com 
Tel) 82-70-4837-1730 Fax) 82-504-056-3833
SKYPE:kictgroup
  
-----Original Message-----

**Comment by RedgooseDev** [comment]
일단 경로 정리는 해뒀습니다.
/ 로 접속하면 redirect로 /helloworld로 이동하도록 수정했어요.

일단 helloworld로 이게 어떻게 작동되고 있는지 확인해보셔야 할 필요가 있을거예요. :)
`/helloworld/index.php` 소스를 확인해보시고 nest_srl을 다른걸로 바꿔보시면 둥지 출력에 대해서 도움이 되실 거예요.

이게 goose만 설치한다고 사진 갤러리가 바로 나오는게 아니고 사진 갤러리나 에디터 같은것들을 따로 설치하고 설정해줘야해요.
커스터마이즈가 쉽도록 만들다보니 직접 수정해야하는것들이 많아서 이해해야 하는것들이 많고 불편한것들이 많은게 사실입니다. ㅠㅠ

이제 삽질이 필요하실 때입니다. :) 화이팅입니다~

**Comment by RedgooseDev** [comment]
그리고 이곳이 공개된 장소이다보니 계정 비밀번호는 꼭!!!! 바꿔주세요!!!!!!!!!

**Comment by moreworld** [comment]
﻿넵 알겠습니다. 감사 합니다.
제가 한번 해 보도록 하겠습니다.
​
​여러가지로 많은 관심 깊이 감사 드립니다. 
  
Best Regards 
President - Heo/YunYoung 
KICT Group | Marketing | moreworld@kictgroup.com | +82-10-9636-3833 
We are Korean high technology manufacturer and exporter. 
Email) moreworld@kictgroup.com, moreworld@marinebio.kr 
Web) www.kictgroup.com 
Tel) 82-70-4837-1730 Fax) 82-504-056-3833
SKYPE:kictgroup
  
-----Original Message-----

**Comment by RedgooseDev** [comment]
넵 막히거나 궁금한게 있으면 다시 이슈에 올려주세요 :0
그럼 이 이슈는 닫도록 하며 좋은하루 되세요~

**Comment by moreworld** [comment]
﻿ 아 그러면 goose 디렉토리를 만들고 그 디렉토리에 goose 파일을 넣고 root 디렉토리에 메인화면을 만들면 되는지요 ?
그렇게 하는데는 고쳐야 할 것이 없는지요 ?
감사합니다.
 
 
Best Regards 
President - Heo/YunYoung 
KICT Group | Marketing | moreworld@kictgroup.com | +82-10-9636-3833 
We are Korean high technology manufacturer and exporter. 
Email) moreworld@kictgroup.com, moreworld@marinebio.kr 
Web) www.kictgroup.com 
Tel) 82-70-4837-1730 Fax) 82-504-056-3833
SKYPE:kictgroup
  
-----Original Message-----

**Comment by RedgooseDev** [comment]
네 메인화면에 방문객에게 보여줄 페이지를 만들어도 되고, 다른 디렉토리 만들어서 프로그램을 만들어도 됩니다. /helloworld/index.php 파일의 소스에서 경로들을 보시면 이해가실겁니다.
