### ISSUE TITLE
인스톨 후에 로그인이 안되서 문의 드립니다.

### ISSUE THREAD

**Issue by s9255025** [RedgooseDev/goose#129]
애플 앨 캐피탄, 아파치, PHP, mySQL 환경 하에서 설치를 진행하였습니다.
인스톨은 아무런 문제 없이 되었고 로그인 화면도 제대로 보여지는데 로그인을 하면 

"The requested URL /goose/auth/login/ was not found on this server." 

이런 메시지가 나오네요.
무엇을 잘못한 것일까요?

설치 경로를 살펴보았더니 goose 디렉토리 아래에 auth라는 디렉토리는 존재하지 않고
소스를 좀 살펴보니 /goose/auth/login, /goose/auth/logout 이라는 디렉토리들도 보이던데...
설치의 문제인가요? 아니면 다른 설정상의 문제일까요?

**Comment by RedgooseDev** [comment]
https://github.com/RedgooseDev/goose/blob/master/.htaccess

.htaccess 숨김파일이 있는데 이 파일이 같이 들어가 있는지 확인해보시겠어요?  
/goose/auth/라는 실질적인 디렉토리는 없고, 라우터 처리되어있습니다. `/module/auth`인것이죠.

.htaccess 파일문제일 가능성이 커 보입니다.

**Comment by s9255025** [comment]
확인해 보니 설치경로 루트에 첨부해 주신 내용의 .htaccess 화일은 존재합니다.

제 설정은
맥 엘 캐피탄에 설치된 기본 apache이고 virtual host 루트의 goose 라는 디렉토리에 git clone 명령어로 설치했었습니다. 아직 문제 해결을 못하고 있네요.

**Comment by RedgooseDev** [comment]
`/goose`는 접속이 되지만 `/goose/abcd/` 형태의 경로로 들어가면 안되는것은 아파치에서 rewriteEngine쪽 문제라고 보여지네요.
그 문제와 비슷한 포스트 링크 걸어드립니다.
https://wordpress.org/support/topic/the-requested-url-login-was-not-found-on-this-server-1

저의 개발환경은 osx 엘캐피탄, mamp를 설치해서 사용하고 있습니다.
https://www.mamp.info/

**Comment by s9255025** [comment]
해결 했습니다. 

말씀하신대로 rewirte 문제였네요
아파치 설정화일에서 mod_rewrite.so 주석 해제하고
AllowOverride All 로 바꿔주니 정상 동작합니다.

갑사합니다^^

**Comment by RedgooseDev** [comment]
다행이네요. :)
호스팅에서는 rewriteEngine이 켜져있는데 직접 설치하는거라서 기본적으로 꺼져있었나봅니다.

잘 안되는부분이 있다면 다시 올려주세요~
