### ISSUE TITLE
최초 설치시 file open fail 메시지가 출력 됩니다.

### ISSUE THREAD

**Issue by nok-cha** [RedgooseDev/goose#130]
권한 문제일까요?

**Comment by RedgooseDev** [comment]
최초 설치에 `file open fail` 메시지가 나온다면 `{GOOSE}/data/`디렉토리 접근권한에 문제있을거라고 보여지네요.
설치할때 자동으로 `{GOOSE}/data/` 디렉토리를 만들고 707 권한변경할텐데... 으으...

`{GOOSE}/data/` 경로로 디렉토리 만들고 권한을 707로 변경해보시겠어요?

**Comment by nok-cha** [comment]
data 경로 만들고 권한 주니까 잘 되네요. 감사합니다.

**Comment by RedgooseDev** [comment]
잘 사용하시고 문제있으면 다시 이슈 올려주세요~
