### ISSUE TITLE
파일이나 디렉토리 접근에 관한 이슈

### ISSUE THREAD

**Issue by RedgooseDev** [RedgooseDev/goose#131]
https://github.com/RedgooseDev/goose/blob/master/module/install/skin/default/transaction_install.php#L45

위와같이 인스톨을 할때 디렉토리를 만드는 과정에서 실패를 할때가 있는데 디렉토리를 만들지 못했을때 오류를 일으키고 진행 중단을 일으켜야할거 같아보임.

-----------------------

https://github.com/RedgooseDev/goose/blob/9bd471439fe86de70666cfec046a0b70561d66a2/core/classes/Util.class.php#L247

`file open fail` 메시지가 뜰때 어떤 경로에서 열지 못했는지 메지지 개선이 필요함.
ex) `file open fail. error location : ./module/install/setting.json`

**Comment by RavenKyu** [comment]
http://stackoverflow.com/questions/109188/how-do-i-check-if-a-directory-is-writeable-in-php

PHP에서의 쓰기가능여부 확인. 
실패하면 안내페이지

**Comment by RedgooseDev** [comment]
a0429312954e7e09bcaafe681417e33f95fb047b
코드적용
