### ISSUE TITLE
슬라이드 모듈스킨 개발

### ISSUE THREAD

**Issue by RedgooseDev** [RedgooseDev/goose#140]
http://src.redgoose.me/article/2162/

업로더 변형작업을 해야하는데 업로더에서 큐 순서변경 기능을 만들면 작업을 할 수 있을거 같음.
플러그인을 개발하거나 기능개선을 해야할듯...

해야할것들이 많아서 다음번으로 미룸

**Comment by RedgooseDev** [comment]
`rg-Uploader` 에서 큐 순서 변경 플러그인은 개발완료

**Comment by redgoose-dev** [comment]
레거시 프로젝트로 변경을 위하여 close
