### ISSUE TITLE
html, css 기술스택 정하기

### ISSUE THREAD

**Issue by RedgooseDev** [RedgooseDev/goose#158]
### HTML
- [ ] html 구조 다시 점검하기
- [ ] 클래스 네이밍 방식 정하기

### CSS
- [ ] 외부 프레임워크를 사용할건지 자체적으로 프레임워크를 만들건지 정하기
- [x] 클래스 네이밍 방식 결정하기 (OOCSS, BEM 등등..)

**Comment by RedgooseDev** [comment]
클래스 네이밍 방식은 `BEM`으로 결정.
이유는 여러번 사용해봐서 익숙해졌기도 하고 컴포넌트에 적합한 클래스 네이밍 방식이라고 보임

**Comment by redgoose-dev** [comment]
레거시 프로젝트로 변경을 위하여 close
