### ISSUE TITLE
파일첨부 용량제한 사용자 조정 가능하게 해야할거 같다.

### ISSUE THREAD

**Issue by RedgooseDev** [RedgooseDev/goose#161]
현재 Article 스킨들에서 용량제한이 임의로 지정되어있는데 File 모듈에서 업로드 용량제한과 연결시켜 줘야할거같아 보인다.
좀 무리겠다 싶으면 Article 세팅파일에 추가해서 접근 거리를 줄이는 방법도 있을거 같다.

**Comment by RavenKyu** [comment]
세션 타임 아웃 같은 건 고려하지 않아도 되려나?

**Comment by RedgooseDev** [comment]
@RavenKyu 용량제한이랑 세션이랑 관계가 없는거 같은데..

**Comment by RedgooseDev** [comment]
154668b9c1d7738fb94d5b77682c4be8dda0cd5e
작업완료
