### ISSUE TITLE
우분투 20.04 에 설치 했는데요

### ISSUE THREAD

**Issue by ksgsu1** [RedgooseDev/goose#167]
화면이 나오지 않습니다. 
확인 부탁드립니다.
http://sub.webend.xyz 입니다.
제가 초보라서요

**Comment by redgoose-dev** [comment]
@ksgsu1 답장이 늦어서 정말 죄송합니다. 안타깝게도 역할별로 프로젝트를 분리해서 다시 만들게 되었습니다.

https://github.com/redgoose-dev/goose-api
