### ISSUE TITLE
동작이 되지 않습니다.

### ISSUE THREAD

**Issue by mirnar1000** [RedgooseDev/goose#75]
안녕하세요. 웹 완전 초보인데, 우연히 개인용 cms로 구글링하다가
데모해보고 완전 마음에 들어서 
1.0 beta 설치를 해보게 되었습니다.

환경은 
윈도우7 64bit XAMPP 최신버전 php 5.6.8 버전입니다.
설치까지는 된거같습니다. db에도 보니까 데이터는 들어와있네요.
근데 설치 끝내고 시작페이지로 가보니 이렇게 나오더군요.

![webshot_20150616_19 53_127_0_0_1_goose__goose admin](https://cloud.githubusercontent.com/assets/12910308/8181409/9d699422-1460-11e5-83b4-72def90e114d.png)

소스 페이지 들어가보니 구체적으로는 이렇게 나왔습니다.

```html


<!DOCTYPE html>
<html>
<head lang="ko">
<meta charset="utf-8">
<title>Goose admin</title>
<meta name="author" content="Goose Admin">
<meta name="generator" content="redgoose">
<meta name="description" content="admin service for goose">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" user-scalable="no">
<link rel="stylesheet" href="/goose/ext/iconFonts/style.css" />
<link rel="stylesheet" href="/goose/module/layout/skin/default/css/layout.css" media="screen" />
<script src="/goose/ext/jQuery/jquery-2.1.3.min.js"></script>
<script>function log(o){console.log(o);}</script>
</head>
<body>

<main role="main">
	<!-- Header -->
	<header id="header">
		<h1><a href="/goose/">Goose</a></h1>
		<nav id="gnb">
			<ul>
				<li><a href='/goose/auth/login/'>Login</a></li>			</ul>
		</nav>
	</header>
	<!-- // Header -->

	<!-- Container -->
	<div id="container">
		<?
		if ($this->pwd_container)
		{
			require_once($this->pwd_container);
		}
		?>
	</div>
	<!-- // Container -->

	<!-- Footer -->
	<footer id="footer">
		<address>Copyright 2015 Goose Engine. All right reserved.</address>
	</footer>
	<!-- // Footer -->
</main>

</body>
</html>
```

**Comment by RedgooseDev** [comment]
답장이 늦어서 정말 죄송합니다. 요즘 전혀 마무리도 짓지 못한채 손도 대지 못하고 있었습니다. ㅠ_ㅠ
소스보기에서 php코드가 본문의 코드와 같이 출력되었다면 php코드가 html로 변환하지 못하고 그대로 출력이 되었다는 의미네요.
```
<?
if ($this->pwd_container)
{
  require_once($this->pwd_container);
}
?>
```

예상하기로는 `<?` 부분에서 그대로 출력해버리는거 같습니다. php세팅을 안했다면 `<?php`키워드가 php로 인식합니다. php최근버전은 은 `<?php`로만 인식하도록 설정되어 있습니다.

http://stackoverflow.com/questions/2185320/how-to-enable-php-short-tags  
링크를 참고하시면 아시겠지만 php.ini 파일에서 `short_open_tag=On` 로 수정하여 해결할 수 있습니다.

사실 개발쪽에서 다 수정을 해야겠지만 수정되어있지 않는 부분들이 많기도 하고 `<?`에 적응되어있어서 깜빡하고 `<?php`로 붙이지 않는 일도 있기때문에 설정을 바꾸는것을 권해드립니다.

**Comment by mirnar1000** [comment]
바쁘신 가운데 도움 드려서 감사합니다^^ 해결되었습니다!
