### ISSUE TITLE
버그 제보합니다.

### ISSUE THREAD

**Issue by swcheon** [RedgooseDev/goose#99]
Nest에서 default(Nest Skin)와 markdown(Article Skin)을 사용하고 있습니다.
글을 쓸 때 역슬래시(\) 문자를 넣어서 작성하면 잘 보이기까지는 하는데, 글을 수정하려 하면 역슬래시가 없어지는 문제가 있습니다. 현재로선 이 문제의 대응책으로 글을 수정할 때 마다 역슬래시가 들어간 부분에 해당 문자를 다시 입력하고 있는데요, 조금 불편하긴 하네요. 확인 부탁드리겠습니다. ^^

**Comment by RedgooseDev** [comment]
제보 감사합니다. 한번 확인해보겠습니다. :)

**Comment by RedgooseDev** [comment]
15e1b4f 수정했습니다.  
뭔가 이유가 있어서 슬래시 제거함수를 넣었던거 같은데 이게 더 문제있는거 같네요.
